# Generated by Django 3.0.4 on 2020-03-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Ho_ten',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
