# Generated by Django 3.0.4 on 2020-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200322_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lich_hen_kham',
            field=models.DateField(blank=True, null=True),
        ),
    ]
