# Generated by Django 3.0.4 on 2020-03-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='important',
            new_name='dau_hong',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='test',
            new_name='ho',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='kho_tho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='met_moi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='sot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='viem_phoi',
            field=models.BooleanField(default=False),
        ),
    ]
