# Generated by Django 3.0.4 on 2020-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200323_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dau_hong',
            new_name='tiepxuc_f0',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='met_moi',
            new_name='tiepxuc_f1',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='viem_phoi',
            new_name='vung_dich',
        ),
        migrations.AddField(
            model_name='todo',
            name='tt_banthan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
