# Generated by Django 3.0.4 on 2020-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200323_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='MSBN',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sdt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
