# Generated by Django 3.0.4 on 2020-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200324_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dau_hong',
            field=models.BooleanField(default=False),
        ),
    ]
