# Generated by Django 3.0.4 on 2020-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_todo_dau_hong'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='buon_non',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='dau_co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='dau_dau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='met_moi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='non',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='ret_run',
            field=models.BooleanField(default=False),
        ),
    ]
