# Generated by Django 3.0.4 on 2020-03-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200325_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='nhiet_do',
            field=models.IntegerField(default=37, null=True),
        ),
    ]
